var baiViet = [];
baiViet ["tieude"] = ["CHIA SẼ TEMPLATE WEBSITE BÁN BÁNH KEM MIỄN PHÍ - SOURCE CODE BAKERY FREE","CÁNH TAY ĐƯỢC IN 3D BIONIC MANG LẠI SỰ TỰ TIN CHO NHỮNG BẠN KHUYẾT TẬT TRẺ TUỔI","PHÓNG THÀNH CÔNG CHIẾC MÁY BAY SIÊU THANH CỦA TỶ PHÚ RICHARD BRANSON LÊN RÌA VŨ TRỤ","TÀU CỨU HỎA ĐẦU TIÊN Ở TRUNG QUỐC ĐƯA VÀO HOẠT ĐỘNG","Anh chàng YouTuber tự chế một chiếc iPhone X từ linh kiện Trung Quốc mua ngoài chợ, chi phí chỉ 500 USD","Realme C1 2019 trình làng, Snapdragon 450, 2GB RAM, camera kép, pin 4.230mAh, giá chỉ từ 2,4 triệu","Bản cập nhật iOS 12.1.3 lại gây lỗi mất kết nối mạng","Bill Gates cam kết đầu tư hàng tỷ USD để xây dựng nhà máy năng lượng hạt nhân thế hệ mới","Oppo đăng ký sáng chế giải pháp che 'nốt ruồi'trên màn hình cực kỳ sáng tạo"];
baiViet ["noidung"] = ["HTML + CSS website bán bánh hoàn toàn miễn phí cho mọi người","Những bạn trẻ không may mắn trong cuộc sống có thể đây sẽ là một niềm vui dành cho họ, để họ được thuận tiện hơn trong làm việc, sinh hoạt và giúp họ được như bao người bình thường khác...","Chiếc máy bay của tỷ phú Richard Branson đưa hai phi công lên rìa vũ trụ thành công, hứa hẹn biến du lịch không gian thành hiện thực.","Hỏa hoạn là một mối nguy hiểm có sức 'hủy diệt' người và tài sản một cách nhanh chóng.","Nếu bạn không muốn mua, thì có thể tự chế cho mình một chiếc iPhone X","Sau nhiều úp mở, Realme chính thức trình làng smartphone mới thuộc phân khúc giá rẻ mang...","Nhà mạng Sprint tại Mỹ đã phải khuyến cáo khách hàng của mình không cập nhật phiên bản iOS 12.1.3.","Bill Gates đã thành lập công ty TerraPower, với sứ mệnh làm thay đổi ngành năng lượng hạt nhân","Đương nhiên, sáng chế này cũng tiết lộ rằng Oppo đang phát triển một mẫu smartphone có màn..."];
document.getElementById("1").innerHTML = baiViet["tieude"][0];
document.getElementById("1.1").innerHTML = baiViet ["noidung"][0];
document.getElementById("2").innerHTML = baiViet["tieude"][1];
document.getElementById("2.1").innerHTML = baiViet ["noidung"][1];
document.getElementById("3").innerHTML = baiViet["tieude"][2];
document.getElementById("3.1").innerHTML = baiViet ["noidung"][2];
document.getElementById("4").innerHTML = baiViet["tieude"][3];
document.getElementById("4.1").innerHTML = baiViet ["noidung"][3];
document.getElementById("5").innerHTML = baiViet["tieude"][4];
document.getElementById("5.1").innerHTML = baiViet ["noidung"][4];
document.getElementById("6").innerHTML = baiViet["tieude"][5];
document.getElementById("6.1").innerHTML = baiViet ["noidung"][5];
document.getElementById("7").innerHTML = baiViet["tieude"][6];
document.getElementById("7.1").innerHTML = baiViet ["noidung"][6]
document.getElementById("8").innerHTML = baiViet["tieude"][7];
document.getElementById("8.1").innerHTML = baiViet ["noidung"][7];
document.getElementById("9").innerHTML = baiViet["tieude"][8];
document.getElementById("9.1").innerHTML = baiViet ["noidung"][8];

